In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /opt/homebrew/Caskroom/miniconda/base/envs/nf_base/lib/python3.9/site-packages (3.1.2)
Requirement already satisfied: et-xmlfile in /opt/homebrew/Caskroom/miniconda/base/envs/nf_base/lib/python3.9/site-packages (from openpyxl) (1.1.0)

In [16]:
# read in excel file and display rows of datset
df = pd.read_excel("Muesli Project raw data.xlsx", sheet_name=['Orders', 'Order Process Data', 'InternData Study', 'Campaign Data'], header=None)

df_orders = df['Orders']
df_process_date = df['Order Process Data']
df_intern = df['InternData Study']
df_campaign = df['Campaign Data']


# Set columns of df_orders based on the second row
df_orders.columns = df_orders.iloc[1]

# Slice df_orders excluding the first two rows
df_orders = df_orders[2:]

# Reset the index of df_orders
df_orders.reset_index(drop=True, inplace=True)
df_orders.head()

1,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit
0,27,CA-2019-121755,2019-01-16 00:00:00,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,90049,West,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.57,3,0,11.7741
1,45,CA-2019-118255,2019-03-11 00:00:00,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,55122,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.98,2,0,19.7714
2,48,CA-2019-169194,2019-06-20 00:00:00,Standard Class,LH-16900,Lena Hernandez,Email,United States,Dover,Delaware,19901,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,45,3,0,4.95
3,60,CA-2019-111682,2019-06-17 00:00:00,First Class,TB-21055,Ted Butterfield,Email,United States,Troy,New York,12180,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,30,2,0,3.3
4,63,CA-2018-135545,2018-11-24 00:00:00,Standard Class,KM-16720,Kunst Miller,Email,United States,Los Angeles,California,90004,West,Special Projects Muesil,Gluten Free,TEC-AC-10004633,13.98,2,0,6.1512

In [17]:
df_process_date

,0,1,2,3,4
0,Row ID,Order ID,Order Date,On Truck Scan Date,Ship Mode
1,3074,CA-2019-125206,2019-01-03 00:00:00,2019-01-07 00:00:00,Express
2,4919,CA-2019-160304,2019-01-02 00:00:00,2019-01-09 00:00:00,Standard Processing
3,4920,CA-2019-160304,2019-01-02 00:00:00,2019-01-09 00:00:00,Standard Processing
4,8604,US-2019-116365,2019-01-03 00:00:00,2019-01-09 00:00:00,Standard Processing
...,...,...,...,...,...
5895,908,CA-2020-143259,2020-12-30 00:00:00,2021-01-06 00:00:00,Standard Processing
5896,909,CA-2020-143259,2020-12-30 00:00:00,2021-01-06 00:00:00,Standard Processing
5897,1297,CA-2020-115427,2020-12-30 00:00:00,2021-01-06 00:00:00,Standard Processing
5898,1298,CA-2020-115427,2020-12-30 00:00:00,2021-01-06 00:00:00,Standard Processing
5899,5092,CA-2020-156720,2020-12-30 00:00:00,2021-01-06 00:00:00,Standard Processing